### ISSUE TITLE
grub patches for other distros

### ISSUE THREAD

**Issue by bjquinn** [zfsonlinux/grub#21]
Are these patches specific to Debian, or is it that the packages are only automatically built for Debian?

If they are not specific to Debian, perhaps we could have packages made for other distros, like say CentOS/RHEL.  If it is possible to manually apply these patches to grub for another distro but auto building the packages is not easy, perhaps we could at least add some notes to the documentation suggesting how one might go about doing it manually.  If someone can let me know I'm not totally barking up the wrong tree and that this is theoretically possible just not yet tested, I would be happy to try it myself and document my findings.

**Comment by FransUrbo** [comment]
Currently, they are in a place that applies them automatically at build time on a Debian GNU/Linux system. Just extracting the relevant patch and adding it to the raw code should work just fine.

The other package maintainers have decided NOT to build 'new, improved grub' with support for the new features. So if you're not running Debian GNU/Linux "you are on your own".

There is ample documentation in the readme branch. It might need improvements, but building grub is quite difficult (strangely enough!). MUCH more so than ZoL. Feel free to send me pull requests against the readme file, or setup a howto.

**Comment by bjquinn** [comment]
Thanks!  I will take a look.
