### ISSUE TITLE
GRUB gets confused when rpool is mirrored

### ISSUE THREAD

**Issue by jgoerzen** [zfsonlinux/grub#6]
When the rpool is mirrored, grub-install gets confused:

<pre>
error: cannot find a GRUB drive for ...
....  Check your device.map.
</pre>

Where "..." and "...." are the names of the devices in the vdev.

I have documented a workaround at http://wiki.complete.org/ConvertingToZFS#Grub_mirrored_rpool_workaround like so:

Create /usr/local/bin/grub-probe, with these contents:

<pre>
 #!/bin/bash

/usr/sbin/grub-probe "$@" | head -1
</pre>

Then run grub-install --grub-probe=/usr/local/bin/grub-probe /dev/blah

**Comment by FransUrbo** [comment]
A better solution (that I created somewhere, somehow - can't find it now though) is in the actual place which generates double entries: <code>grub-mkconfig</code>:

```
GRUB_DEVICE="`${grub_probe} --target=device /`"
```

Gives on my test system:

```
debian:~# grub-probe --target=device /
/dev/sdb1
/dev/sdc1
```

So the 'correct' solution would be to modify the <code>grub-mkconfig</code> line so that it reads:

```
GRUB_DEVICE="`${grub_probe} --target=device / | head -n1`"
```

**Comment by FransUrbo** [comment]
Fixed in tag 'master/debian/wheezy/2.00-22debian1+zfs3+0.6.3-2_wheezy'. Building package now and will upload to wheezy-daily within the hour.

**Comment by FransUrbo** [comment]
@dajhorn I consider the solution fixed, so when/if you have fixed it for Ubuntu, would you mind closing the issue?

**Comment by dajhorn** [comment]
Ubuntu is not going to backport handling for this GRUB enhancement.  (ie: How `grub-probe` now prints each component name in a composite device.)

Until distro integrates this new feature, it follows that users must still manually install the stage1 loader to each element in a RAID array; ZFS or not.
